### ISSUE TITLE
Cannot join dedicated servers [1.21.1]

### ISSUE THREAD

**Issue by ArmoredFuzzball** [CartConnoisseur/DeadSimpleBags#1]
Cannot join dedicated server because of registries in this mod (even with mod on client too).
Mod version v1.1.0
See error below:
```
[12:49:58] [Render thread/ERROR]: Received unknown remote registry entries from server
[12:49:58] [Render thread/ERROR]: Registry entry (deadsimplebags:open) is missing from local registry (minecraft:data_component_type)
[12:49:58] [Render thread/ERROR]: Registry entry (deadsimplebags:pickup_mode) is missing from local registry (minecraft:data_component_type)
[12:49:58] [Render thread/ERROR]: Registry remapping failed!
java.util.concurrent.CompletionException: net.fabricmc.fabric.impl.registry.sync.RemapException: Received 2 registry entries that are unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

deadsimplebags

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:144) ~[fabric-registry-sync-v0-5.1.2+60c3209b19-b7f5d725517833f3.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: net.fabricmc.fabric.impl.registry.sync.RemapException: Received 2 registry entries that are unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

deadsimplebags

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:359) ~[fabric-registry-sync-v0-5.1.2+60c3209b19-b7f5d725517833f3.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:259) ~[fabric-registry-sync-v0-5.1.2+60c3209b19-b7f5d725517833f3.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:141) ~[fabric-registry-sync-v0-5.1.2+60c3209b19-b7f5d725517833f3.jar:?]
	... 14 more
[12:49:58] [Render thread/WARN]: Client disconnected with reason: Received 2 registry entries that are unknown to this client.
```

**Comment by XaaRii** [comment]
bump, I have the same issue. I have to play on vanilla client to even connect to the server...
I've noticed that even adding the mod on client-side doesn't change a thing, in fact it is not even recognized by mod menu.

Any fixes/suggestions would be greatly appreciated, this mod is exactly the type of mod we were looking for, works well, looks really nice (thanks to using the bundle item) and doesn't bring in any weird/useless functionality as most other mods of this type. Keep up the good work!

**Comment by CartConnoisseur** [comment]
Sorry for the *super* late reply (I took a rather long break from modding shortly after originally publishing this mod), this issue has been resolved in the latest versions :)
